name: coverager

on:
  push:
    branches: ["main"]
    paths:
      - "**.jsx?"
      - "**.tsx?"
      - "lib/**"
      - "test/**"
      - "package.json"
      - ".github/workflows/coverager.yml"
  pull_request:
    paths:
      - "**.jsx?"
      - "**.tsx?"
      - "lib/**"
      - "test/**"
      - "package.json"
      - ".github/workflows/coverager.yml"

env:
  CI: true

jobs:
  coverage:
    uses: uiolee/workflows/.github/workflows/coverage.yml@main

